global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: snmp
    metrics_path: /snmp
    static_configs:
      - targets:
          - 127.0.10.10
          - 127.0.10.11
          - 127.0.10.12
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __param_module
        replacement: if_mib
      - target_label: __param_auth
        replacement: public_v2
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: identity
      - target_label: __address__
        replacement: localhost:9116
