global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: wisp-snmp
    metrics_path: /snmp
    static_configs:
      - targets:
          - 172.31.250.21
          - 172.31.250.22
          - 172.31.250.23
          - 172.31.250.24
          - 172.31.250.25
          - 172.31.250.26
          - 172.31.250.27
          - 172.31.250.28
          - 172.31.250.29
          - 172.31.250.30
          - 172.31.250.31
          - 172.31.250.32
          - 172.31.250.33
          - 172.31.250.34
          - 172.31.250.35
          - 172.31.250.36
          - 172.31.250.37
          - 172.31.250.38
          - 172.31.250.39
          - 172.31.250.40
          - 172.31.250.41
          - 172.31.250.42
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __param_module
        replacement: if_mib
      - target_label: __param_auth
        replacement: public_v2
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: identity
      - target_label: __address__
        replacement: wisp-snmp-exporter:9117
